# Generated by Django 5.0.4 on 2024-07-04 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_record'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='record_table',
        ),
    ]
